### ISSUE TITLE
Error reading from S3

### ISSUE THREAD

**Issue by bmcfeely** [newrelic/aws-log-ingestion#6]
It looks like there might be a bug in https://github.com/newrelic/aws-log-ingestion/blob/master/src/function.py#L183 when reading s3 — I think (I’m not super Python-savvy) that `_get_s3_data` returns a byte array, and I think the code in lambda_handler expects it to be a string (using `.splitlines()`)

The stack trace looks like:
```a bytes-like object is required, not 'str': TypeError
Traceback (most recent call last):
File "/var/task/function.py", line 496, in lambda_handler
_send_log_entry(log_line, context)
File "/var/task/function.py", line 203, in _send_log_entry
entry_type = _get_entry_type(log_entry)
File "/var/task/function.py", line 309, in _get_entry_type
if '"logGroup":"/aws/vpc/flow-logs"' in log_entry:
TypeError: a bytes-like object is required, not 'str'
```

Steps to reproduce:
* Hook up the lambda to an S3 bucket (I'm not sure it matters which events you choose to trigger on, as long as there's data in the bucket)
* Check the output of this Lambda

**Comment by leandrommoliveira** [comment]
I have the same problem this work for me.

```
def _get_s3_data(bucket, key):
    '''
    This function gets a specific log file from the given S3 bucket and
    decompresses it.
    '''
    s3_client = boto3.client('s3')
    data = s3_client.get_object(Bucket=bucket, Key=key)['Body'].read()

    #if key.split('.')[-1] == 'gz':
    data = gzip.GzipFile(fileobj=BytesIO(data)).read().decode("utf-8")

    return data
```
